default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("PG_USERNAME") { 'store' } %>
  password: <%= ENV.fetch("PG_PASSWORD") { 'store' } %>
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>

development:
  <<: *default
  database: database

test:
  <<: *default
  database: database_t
