default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV.fetch("PG_HOST") { 'localhost' } %>

development:
  <<: *default
  database: database

test:
  <<: *default
  database: database_t
